### ISSUE TITLE
pocha to take a path to a python file as an argument.

### ISSUE THREAD

**Issue by BlauBaron** [rlgomes/pocha#14]
pocha seems not to like when the python file with the tests is in a relative location to pocha:
using both pypi and building from source I get the following:
~~~bash
$: pocha ../tests/unit_test.py                                                      [ruby-2.4.2p198]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pocha", line 11, in <module>
    load_entry_point('pocha==0.13.0', 'console_scripts', 'pocha')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pocha/cli.py", line 26, in cli
    tests = discover.search(path, expression)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pocha/discover.py", line 89, in search
    __import__(name)
ValueError: Empty module name
~~~

**Comment by rlgomes** [comment]
@bjornefitte I'll see if I can fix this up later this week
